version: '3.4'

services:
  combis-app:
    image: combis-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/app